### ISSUE TITLE
Blog Archive Issues

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#1]
Had to de-activate the flagging capabilities on the blog archive because the text from the the flag description is getting duplicated within the post content.

![mod issue](https://cloud.githubusercontent.com/assets/480667/7213281/917cf35a-e546-11e4-89a5-12a8125a19c9.png)

**Comment by r-a-y** [comment]
I cannot duplicate this locally.

![screenshot](https://cloud.githubusercontent.com/assets/505921/7327389/96770ef0-ea81-11e4-9783-dcaf665f41b8.png)

I'm guessing it's a caching issue.  Can you try clearing the cache from the easyPress dashboard?

**Comment by mrjarbenne** [comment]
This pre-dates easypress, and any caching. I'll try again.

**Comment by r-a-y** [comment]
It could be a theme issue.  Does this problem occur on other themes?

**Comment by mrjarbenne** [comment]
Seems to be a theme issue that has been recified in an update since I took the screenshot and turned it off. It was in TwentyTen. 

Could the link be less overt? Could it just be added to the post meta, and match the CSS of that item. Like these "Promote to Main Site" links are from the wp-curator plugin

![2015-04-26_20-28-25](https://cloud.githubusercontent.com/assets/480667/7340065/d9b5b1bc-ec52-11e4-8b55-e662873da472.png)

**Comment by r-a-y** [comment]
I plan on looking at these bp-moderation issues later in the week.  Need to finish up some stuff for the next BP beta.

**Comment by r-a-y** [comment]
After looking into trying to inject the mod link after the `Edit` post link, it doesn't look like it is possible to do this because WP adds a check to see if the logged-in user user can edit the current post before we are able to filter the `Edit` link to add our one.

Since we'd want all users to access the `Flag this post as inappropriate` link, this will not work for our needs.  Looks like we're stuck with the current display method.

**Comment by mrjarbenne** [comment]
If we are stuck, can we make it less overt? On a blog, it's pretty obnoxious. I assume we can't tag it beside the site meta instead, which should show up regardless of user role. 

![2015-06-03_12-40-42](https://cloud.githubusercontent.com/assets/480667/7965851/1fb783b2-09ee-11e5-908e-e402f6240f44.png)

**Comment by r-a-y** [comment]
>  I assume we can't tag it beside the site meta instead, which should show up regardless of user role.

We cannot place any link after the "Edit" link because placing links after the "Edit" link is tied to post author permissions, meaning only the post author, editor or admin would be able to see the link and we want all users to access the "Flag" link.

What do you mean by "site meta"?

**Comment by mrjarbenne** [comment]
By site meta I mean that line of text at the bottom where the date appears and the leave a comment link appears in the 2015 example above (https://codex.wordpress.org/Meta_Tags_in_WordPress). Here's another example, using the Singl theme, which places a permalink in the meta:

http://www.screencast.com/t/lrfRdznRbte

**Comment by r-a-y** [comment]
Thanks for the screencast.

It's potentially possible to hook into the "Leave a comment" link as shown in the screenshot above, but the "Flag" link would only show up before "Leave a comment", not after.  Would this be okay?

**Comment by mrjarbenne** [comment]
I think that's fine. The order doesn't really matter.

**Comment by r-a-y** [comment]
One problem is this technique will not work if the post is password protected or if the number of comments is zero and if comments are closed.  I'm going to push a commit so you can test.

Also this technique will not work with pages since pages do not use comments on a default install of WP.  Can pages continue to use the old method?

**Comment by mrjarbenne** [comment]
In 2015 it's sandwiched between the genericon and the number of comments:

![2015-06-04_00-13-43](https://cloud.githubusercontent.com/assets/480667/7977552/f28d6692-0a59-11e5-8407-5cbcbf26e62b.png)

Despite that, It definitely looks better down there, but that is a number of caveats isn't it. Password protected I could live with as it's not a popular thing, but the comments being zero and comments being closed may constitute a large number of posts that would potentially be un-reportable.  We can leave pages the way that they are if there isn't an option. It's not as intrusive as when it's repeated over and over in excerpts down your blog feed.

This seems extreme, but would it be better if I could add a call to it by editing each of the themes on the Commons?

**Comment by r-a-y** [comment]
Twentyfifteen wraps the `comments_popup_link()` function around its own `<span>` tag.  Nothing I can do about that I'm afraid.

I think we should revert the change and go back to what BP Moderation was doing before.  Changing all themes to add an action seems really extreme and not good for theme upgrade maintenance, unless you made a child theme of each theme.

The only other thing I can think of is to dynamically move the "Flag" link using JS and to somehow find where the post meta is on the page.  This will be hard because each theme has different markup.  Will see what I can do.

**Comment by mrjarbenne** [comment]
What if we styled the button better. Look at the tweet button from the official twitter plugin https://wordpress.org/plugins/twitter/
It's active here: http://dev.commons.hwdsb.on.ca/2015/06/03/ch-ch-ch-ch-changes/

Could we use something like this and drop it after the post: http://necolas.github.io/css3-github-buttons/
Just a flag icon and the word Flag?

What if it was an option in a bank of buttons, so it didn't look stranded. This is full on scope creep, and it's 3am, so it might be the tired talking... but what if under each post had a flag button, a follow blog button (moved or duplicated from the bottom right) and a re-blog button (feature request!), like the Share buttons added by plugins like jetpack:

![2015-06-04_03-06-17](https://cloud.githubusercontent.com/assets/480667/7978816/9fe7430a-0a67-11e5-9fae-bf210cb2ce3e.png)

Don't commit anything else just yet. Let's think about this more. I'll keep looking at how other buttons are added to sites.

**Comment by mrjarbenne** [comment]
Perhaps it would make sense in opposition to a "Like" button. https://github.com/JonMasterson/WordPress-Post-Like-System

**Comment by mrjarbenne** [comment]
DJ Paul had created a Like infrastructure in BP Labs that we could use. Just need to move it from the admin bar: https://github.com/r-a-y/BP-Labs

**Comment by r-a-y** [comment]
I've rolled things back to the way things were before I moved the "Flag" link since there are too many issues.

If we want to add a bunch of buttons such as the Like button from BP Labs to the end of a post, then that is indeed a separate issue from BP Moderation.  Let's open a new issue to track that.

**Comment by mrjarbenne** [comment]
I'm just spitballing. Not sure which direction I want to go. Moving back is a good move. Too many exceptions that don't reveal the link when it's tied to the comments. 
#5

**Comment by mrjarbenne** [comment]
Closing this. Conversation has moved to enhancements in main repo.
