### ISSUE TITLE
Flag on Multisite Posts Placement Issue

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/BP-Moderation#16]
In the twenty-twenty, and now the new twenty-twenty-one theme, the flag button is falling outside of the entry-content div off to the side: 

![2020-12-11_14-57-16](https://user-images.githubusercontent.com/480667/101949911-5de64b80-3bc2-11eb-9f7d-6b2def1bebca.png)

**Comment by r-a-y** [comment]
The `twentytwenty` and `twentytwentyone` themes require a paragraph to wrap around the links in order to look decent.

I'm wondering whether we should wrap a `<p>` element around the link across all themes or just specific to the `twentytwenty` and `twentytwentyone` themes. I've gone with the latter approach for now. This is available for testing on production.
